---
title: "data-viz-practice"
author: "Maddy Enda"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

#adding packages 
```{r}
library(tidyverse)
library(here)
library(janitor)

install.packages("ggrepel")
install.packages("gghighlight")
install.packages( "paletteer")
install.packages( "ggExtra")
install.packages( "ggbeeswarm")
install.packages("patchwork")

```

#loading installed packages
```{r}
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(patchwork)
```

#starting data visualization
```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))

ggplot(data= lizards, aes(x= total_length, y= weight)) +geom_point() + geom_line()

ggplot() + geom_point( data= lizards, aes(x=total_length, y=weight)) 
```


```{r}
ggplot(data= lizards, aes(y= common_name, x= weight)) +geom_jitter() 
```

```{r}
ggplot(data= lizards, aes(x= weight)) + geom_histogram(
  color= "cyan", 
  fill= "pink", 
  linewidth= 2,
  linetype= "dotted"
  )
```


```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) + geom_point(
  color= "#DDC3D0", 
  fill= "#3E92CC", 
  shape= 22,
  size= 3,
  alpha = 0.2
  )
```

```{r}
ggplot( lizards, aes(x= total_length, y= weight)) + geom_point(aes(color= common_name, 
                size= total_length ), 
                alpha= 1) +
  scale_color_discrete( type=
                        c("#AA4465", "#EDF0DA",  "#EDF0DA",  "#EDF0DA",  "#EDF0DA",  "#EDF0DA",  "#EDF0DA"))
```


```{r}
ggplot(data= lizards, aes( x= site, y= weight)) + geom_jitter(aes(color= common_name)) +theme_bw()
```

```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point() + 
  labs(x= "Total length (mm)", y= "Weight (grams)", title= "Lizard Size")
```


```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point() + 
  facet_wrap(~common_name, ncol= 3, scales= "free") +
  labs(x= "Total length (mm)", y= "Weight (grams")
```

```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point() + 
  facet_grid( sex ~ tail)
```


```{r}
lizards_count <- lizards %>%
  count(common_name)

ggplot( lizards_count, aes(y= fct_reorder(common_name,n), x= n)) +
  geom_col()
```

```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point(aes(color= common_name, shape= common_name), 
             size= 2) + 
  theme_minimal() +
  labs( x= "Total length (mm)", y= "Weight (grams)",
        color= "Lizard Species") +
  facet_wrap(~ common_name, scales = "free")
```

```{r}
ggplot( data= lizards, aes(y = fct_infreq(common_name))) + geom_bar(aes(fill= site)) + 
  theme_minimal() +
  labs(x= "Lizard counts",
       y= "Species (common name)") +
  facet_grid(sex~tail)
  
```


#session 2 work
```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 500, by= 250), 
                     limits = c(0,500)) +
  scale_y_continuous( breaks = seq(from= 0, to= 70, by= 10),
                      limits = c(0, 70)) + theme_light()
```

#scaling dates
```{r}
lizards_counts <- lizards %>%
  mutate(date= lubridate::mdy(date)) %>%
  count(date)

ggplot(data= lizards_counts, aes(x= date, y= n)) +
  geom_line() +
  scale_x_date(breaks = scales::breaks_width("3 years"),
               labels= scales:: label_date("%Y"))
```


```{r}
ggplot(data= lizards, aes(x= total_length, y= weight)) +
  geom_point(aes(color= total_length)) +
  scale_color_steps2(low= "green", mid= "white", high= "red", midpoint= 150, breaks= c(50,75,150,180, 220, 280)) +
  geom_hline(yintercept= mean(lizards$weight), color= "blue", linetype= "dashed") +
  annotate( "text", x= 350, y= mean(lizards$weight), label= "Mean Weight")
```


```{r}
mono <- read_csv(here("data_tidy", "mono.csv"))

ggplot( data= mono, aes(x=year, y= lake_level)) + 
  geom_rect(aes(xmin= 1941, 
                xmax= 1983, 
                ymin= 6350,
                ymax= 6440),
            fill= "lightblue", alpha= 0.1) +
geom_line() +
  labs( x= "Year",
        y= "Lake surface level\n(feet above sea level)\n",
        title= "Mono Lake (1850-2017)",
        caption= "Data: Mono Basin Clearinghouse") +
  scale_y_continuous(limits= c(6350, 6440),
                     breaks= c(6370, 6400, 6430),
                     labels = scales::label_comma()) +
  scale_x_continuous(limits= c(1850, 2020),
                     breaks= seq(1850, 2010, by= 20), 
                     expand = c(0,0)) +
  geom_hline( yintercept= 6360, linetype = "dashed") +
  annotate("text", x= 1910, y= 6370, 
           label= "Decreased shrimp abundance expected \n(6,360 feet above sea level)") +
  annotate( "text", x= 1962, y= 6425,
            label= "unrestricted diversions\n (1941-1983)",
            size= 3) +
  theme_minimal()
  
```

